//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlinesAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationDetail
    {
        public string PNRNo { get; set; }
        public int PassengerNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual ReservationMaster ReservationMaster { get; set; }
    }
}
