//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlinesAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservationMaster()
        {
            this.ReservationDetails = new HashSet<ReservationDetail>();
        }
    
        public string PNRNo { get; set; }
        public string FlightNo { get; set; }
        public Nullable<System.DateTime> TravelDate { get; set; }
        public Nullable<int> NoOfPassengers { get; set; }
    
        public virtual FlightSchedule FlightSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationDetail> ReservationDetails { get; set; }
    }
}
